ALTER TYPE SURVEY_EVENT_TYPE RENAME VALUE 'StartIntro' TO 'OpenFileBinary';
ALTER TYPE SURVEY_EVENT_TYPE RENAME VALUE 'EndIntro' TO 'OpenFileSpreadsheet';

ALTER TYPE SURVEY_EVENT_TYPE ADD VALUE 'CloseFileBinary';
ALTER TYPE SURVEY_EVENT_TYPE ADD VALUE 'CloseFileSpreadsheet';
