ALTER TYPE SURVEY_EVENT_TYPE RENAME VALUE 'OpenFileBinary' TO 'OpenImageBinary';
ALTER TYPE SURVEY_EVENT_TYPE RENAME VALUE 'OpenFileSpreadsheet' TO 'OpenVideoBinary';
ALTER TYPE SURVEY_EVENT_TYPE RENAME VALUE 'CloseFileBinary' TO 'OpenPdfBinary';
ALTER TYPE SURVEY_EVENT_TYPE RENAME VALUE 'CloseFileSpreadsheet' TO 'OpenSpreadsheet';
ALTER TYPE SURVEY_EVENT_TYPE RENAME VALUE 'OpenReferenceBookBinary' TO 'CloseImageBinary';

ALTER TYPE SURVEY_EVENT_TYPE ADD VALUE 'CloseVideoBinary';
ALTER TYPE SURVEY_EVENT_TYPE ADD VALUE 'ClosePdfBinary';
ALTER TYPE SURVEY_EVENT_TYPE ADD VALUE 'CloseSpreadsheet';
