ALTER TYPE SURVEY_EVENT_TYPE ADD VALUE 'StartSurveyCommand';
ALTER TYPE SURVEY_EVENT_TYPE ADD VALUE 'EndSurveyCommand';
ALTER TYPE SURVEY_EVENT_TYPE ADD VALUE 'StartScenarioCommand';
ALTER TYPE SURVEY_EVENT_TYPE ADD VALUE 'StartQuestionnaireCommand';
ALTER TYPE SURVEY_EVENT_TYPE ADD VALUE 'SendSupervisorChatMessage';
ALTER TYPE SURVEY_EVENT_TYPE ADD VALUE 'SendParticipantChatMessage';
