ALTER TYPE SURVEY_EVENT_TYPE ADD VALUE 'SelectImageBinary';
ALTER TYPE SURVEY_EVENT_TYPE ADD VALUE 'SelectVideoBinary';
ALTER TYPE SURVEY_EVENT_TYPE ADD VALUE 'SelectPdfBinary';
ALTER TYPE SURVEY_EVENT_TYPE ADD VALUE 'SelectSpreadsheet';
ALTER TYPE SURVEY_EVENT_TYPE ADD VALUE 'SelectTextDocument';
