ALTER TYPE SURVEY_EVENT_TYPE ADD VALUE 'UpdateSpreadsheetCellValue';
ALTER TYPE SURVEY_EVENT_TYPE ADD VALUE 'UpdateSpreadsheetCellType';
ALTER TYPE SURVEY_EVENT_TYPE ADD VALUE 'SelectSpreadsheetCell';
ALTER TYPE SURVEY_EVENT_TYPE ADD VALUE 'AddSpreadsheetColumn';
ALTER TYPE SURVEY_EVENT_TYPE ADD VALUE 'AddSpreadsheetRow';
ALTER TYPE SURVEY_EVENT_TYPE ADD VALUE 'RemoveSpreadsheetColumn';
ALTER TYPE SURVEY_EVENT_TYPE ADD VALUE 'RemoveSpreadsheetRow';
ALTER TYPE SURVEY_EVENT_TYPE ADD VALUE 'SelectSpreadsheetCellRange';
