import {range} from "lodash-es"
import {binaryFileMock} from "../../../../components/binary-upload-input/__mocks__/binary-file.mock"
import {ErpType} from "../../../../enums"
import {ErpComponent} from "../../../../models"

export const createErpMockEntities = (count: number): Array<ErpComponent> =>
  range(count).map(id => ({
    type: ErpType.Component,
    id,
    name: `Komponente ${id}`,
    category: `Kategorie ${id}}`,
    purchasingPriceInCents: Math.floor(100 + Math.random() * 300),
    margin: Math.floor(100 + Math.random() * 300),
    supplierId: Math.floor(100000 + Math.random() * 500000),
    packSize: Math.floor(10 + Math.random() * 30),
    availableStock: Math.floor(10 + Math.random() * 70),
    stockCostPerUnitInCents: Math.floor(100 + Math.random() * 300),
    stockCostTotalInCents: Math.floor(1000 + Math.random() * 3000),
    unit: "€",
    note: id % 2 === 0 ? null : "eine notiz",
    sampleCompanyId: `123-${id}`,
    binaryFileId: id % 2 !== 0 ? null : `12341-${id}`,
    binaryFile: id % 2 !== 0 ? null : binaryFileMock
  }))

export const erpComponentMockEntities: Array<ErpComponent> = [
  {
    type: ErpType.Component,
    id: 0,
    name: "Komponente 0",
    category: "Kategorie 0",
    purchasingPriceInCents: 206,
    margin: 383,
    supplierId: 211867,
    packSize: 37,
    availableStock: 40,
    stockCostPerUnitInCents: 222,
    stockCostTotalInCents: 2680,
    unit: "€",
    note: null,
    sampleCompanyId: "123-0",
    binaryFileId: "12341-0",
    binaryFile: binaryFileMock
  },
  {
    type: ErpType.Component,
    id: 1,
    name: "Komponente 1",
    category: "Kategorie 1",
    purchasingPriceInCents: 107,
    margin: 251,
    supplierId: 166788,
    packSize: 26,
    availableStock: 37,
    stockCostPerUnitInCents: 117,
    stockCostTotalInCents: 1369,
    unit: "€",
    note: "eine notiz",
    sampleCompanyId: "123-1",
    binaryFileId: null,
    binaryFile: null
  },
  {
    type: ErpType.Component,
    id: 2,
    name: "Komponente 2",
    category: "Kategorie 2",
    purchasingPriceInCents: 265,
    margin: 200,
    supplierId: 335329,
    packSize: 34,
    availableStock: 55,
    stockCostPerUnitInCents: 337,
    stockCostTotalInCents: 3998,
    unit: "€",
    note: null,
    sampleCompanyId: "123-2",
    binaryFileId: "12341-2",
    binaryFile: binaryFileMock
  },
  {
    type: ErpType.Component,
    id: 3,
    name: "Komponente 3",
    category: "Kategorie 3",
    purchasingPriceInCents: 130,
    margin: 174,
    supplierId: 372279,
    packSize: 33,
    availableStock: 21,
    stockCostPerUnitInCents: 300,
    stockCostTotalInCents: 2687,
    unit: "€",
    note: "eine notiz",
    sampleCompanyId: "123-3",
    binaryFileId: null,
    binaryFile: null
  },
  {
    type: ErpType.Component,
    id: 4,
    name: "Komponente 4",
    category: "Kategorie 4",
    purchasingPriceInCents: 393,
    margin: 118,
    supplierId: 594181,
    packSize: 36,
    availableStock: 52,
    stockCostPerUnitInCents: 235,
    stockCostTotalInCents: 3114,
    unit: "€",
    note: null,
    sampleCompanyId: "123-4",
    binaryFileId: "12341-4",
    binaryFile: binaryFileMock
  },
  {
    type: ErpType.Component,
    id: 5,
    name: "Komponente 5",
    category: "Kategorie 5",
    purchasingPriceInCents: 190,
    margin: 376,
    supplierId: 459522,
    packSize: 36,
    availableStock: 65,
    stockCostPerUnitInCents: 152,
    stockCostTotalInCents: 2658,
    unit: "€",
    note: "eine notiz",
    sampleCompanyId: "123-5",
    binaryFileId: null,
    binaryFile: null
  },
  {
    type: ErpType.Component,
    id: 6,
    name: "Komponente 6",
    category: "Kategorie 6",
    purchasingPriceInCents: 370,
    margin: 212,
    supplierId: 470298,
    packSize: 22,
    availableStock: 43,
    stockCostPerUnitInCents: 129,
    stockCostTotalInCents: 3243,
    unit: "€",
    note: null,
    sampleCompanyId: "123-6",
    binaryFileId: "12341-6",
    binaryFile: binaryFileMock
  },
  {
    type: ErpType.Component,
    id: 7,
    name: "Komponente 7",
    category: "Kategorie 7",
    purchasingPriceInCents: 159,
    margin: 163,
    supplierId: 360010,
    packSize: 22,
    availableStock: 37,
    stockCostPerUnitInCents: 194,
    stockCostTotalInCents: 2493,
    unit: "€",
    note: "eine notiz",
    sampleCompanyId: "123-7",
    binaryFileId: null,
    binaryFile: null
  },
  {
    type: ErpType.Component,
    id: 8,
    name: "Komponente 8",
    category: "Kategorie 8",
    purchasingPriceInCents: 324,
    margin: 232,
    supplierId: 292512,
    packSize: 22,
    availableStock: 51,
    stockCostPerUnitInCents: 298,
    stockCostTotalInCents: 1975,
    unit: "€",
    note: null,
    sampleCompanyId: "123-8",
    binaryFileId: "12341-8",
    binaryFile: binaryFileMock
  },
  {
    type: ErpType.Component,
    id: 9,
    name: "Komponente 9",
    category: "Kategorie 9",
    purchasingPriceInCents: 334,
    margin: 396,
    supplierId: 520108,
    packSize: 11,
    availableStock: 58,
    stockCostPerUnitInCents: 255,
    stockCostTotalInCents: 2846,
    unit: "€",
    note: "eine notiz",
    sampleCompanyId: "123-9",
    binaryFileId: null,
    binaryFile: null
  }
]
