import {ErpType} from "../../../src/enums"
import {ErpEmployeeFragment} from "../../../src/graphql/generated/ErpEmployeeFragment"
import {EmploymentMode, FamilyStatus, Salutation} from "../../../src/graphql/generated/globalTypes"
import {ErpEmployee} from "../../../src/models"
import {sampleCompanyIdMock} from "./common"

export const erpEmployeesMockGraphQl: ErpEmployeeFragment[] = [
  {
    __typename: "ErpEmployee",
    id: 1,
    salutation: Salutation.Mr,
    firstName: "Marco",
    lastName: "Fürst",
    addressLine: "Ruschestrasse 51",
    postalCode: "39303",
    city: "Genthin",
    country: "Germany",
    email: "MarcoFurst@teleworm.us",
    phone: "03933243334",
    department: "Department of Defense",
    jobTitle: "Welding worker",
    employmentMode: EmploymentMode.FullTime,
    employedAt: "2020-08-13 11:22:15.468000 +00:00",
    employmentEndsAt: null,
    site: "HQ",
    graduation: "Meister",
    furtherEducation: ["Gesellenbrief", "Meisterbrief"],
    taxClass: "1",
    familyStatus: FamilyStatus.Single,
    childCount: 0,
    sampleCompanyId: sampleCompanyIdMock,
    binaryFileId: null,
    note: "note",
    binaryFile: null
  },
  {
    __typename: "ErpEmployee",
    id: 2,
    salutation: Salutation.Mrs,
    firstName: "Barbara",
    lastName: "Bar",
    addressLine: "Rankestraße 1",
    postalCode: "82067",
    city: "Ebenhausen",
    country: "Germany",
    email: "BarbaraBar@dayrep.com",
    phone: "08453759136",
    department: "Mail",
    jobTitle: "Mail carrier",
    employmentMode: EmploymentMode.PartTime,
    employedAt: "2020-08-13 11:22:15.468000 +00:00",
    employmentEndsAt: null,
    site: "Central",
    graduation: "Fachkraft für Postdienstleistungen",
    furtherEducation: ["Fachkraft für Postdienstleistungen"],
    taxClass: "4",
    familyStatus: FamilyStatus.Married,
    childCount: 2,
    sampleCompanyId: sampleCompanyIdMock,
    binaryFileId: null,
    note: "note",
    binaryFile: null
  },
  {
    __typename: "ErpEmployee",
    id: 3,
    salutation: Salutation.Mrs,
    firstName: "Klaudia",
    lastName: "Glockner",
    addressLine: "Hardenbergstraße 1",
    postalCode: "76891",
    city: "Bundenthal",
    country: "Germany",
    email: "KlaudiaGlockner@rhyta.com",
    phone: "06394246495",
    department: "Media",
    jobTitle: "Media specialist",
    employmentMode: EmploymentMode.FullTime,
    employedAt: "2020-08-13 11:22:15.468000 +00:00",
    employmentEndsAt: null,
    site: "HQ",
    graduation: "M.A.",
    furtherEducation: ["B.A.", "M.A."],
    taxClass: "2",
    familyStatus: FamilyStatus.Divorced,
    childCount: 1,
    sampleCompanyId: sampleCompanyIdMock,
    binaryFileId: null,
    note: "note",
    binaryFile: null
  }
]

export const erpEmployeesMock: ErpEmployee[] = [
  {
    type: ErpType.Employee,
    id: 1,
    salutation: Salutation.Mr,
    firstName: "Marco",
    lastName: "Fürst",
    addressLine: "Ruschestrasse 51",
    postalCode: "39303",
    city: "Genthin",
    country: "Germany",
    email: "MarcoFurst@teleworm.us",
    phone: "03933243334",
    department: "Department of Defense",
    jobTitle: "Welding worker",
    employmentMode: EmploymentMode.FullTime,
    employedAt: "2020-08-13 11:22:15.468000 +00:00",
    employmentEndsAt: null,
    site: "HQ",
    graduation: "Meister",
    furtherEducation: ["Gesellenbrief", "Meisterbrief"],
    taxClass: "1",
    familyStatus: FamilyStatus.Single,
    childCount: 0,
    sampleCompanyId: sampleCompanyIdMock,
    binaryFileId: null,
    note: "note",
    binaryFile: null
  },
  {
    type: ErpType.Employee,
    id: 2,
    salutation: Salutation.Mrs,
    firstName: "Barbara",
    lastName: "Bar",
    addressLine: "Rankestraße 1",
    postalCode: "82067",
    city: "Ebenhausen",
    country: "Germany",
    email: "BarbaraBar@dayrep.com",
    phone: "08453759136",
    department: "Mail",
    jobTitle: "Mail carrier",
    employmentMode: EmploymentMode.PartTime,
    employedAt: "2020-08-13 11:22:15.468000 +00:00",
    employmentEndsAt: null,
    site: "Central",
    graduation: "Fachkraft für Postdienstleistungen",
    furtherEducation: ["Fachkraft für Postdienstleistungen"],
    taxClass: "4",
    familyStatus: FamilyStatus.Married,
    childCount: 2,
    sampleCompanyId: sampleCompanyIdMock,
    binaryFileId: null,
    note: "note",
    binaryFile: null
  },
  {
    type: ErpType.Employee,
    id: 3,
    salutation: Salutation.Mrs,
    firstName: "Klaudia",
    lastName: "Glockner",
    addressLine: "Hardenbergstraße 1",
    postalCode: "76891",
    city: "Bundenthal",
    country: "Germany",
    email: "KlaudiaGlockner@rhyta.com",
    phone: "06394246495",
    department: "Media",
    jobTitle: "Media specialist",
    employmentMode: EmploymentMode.FullTime,
    employedAt: "2020-08-13 11:22:15.468000 +00:00",
    employmentEndsAt: null,
    site: "HQ",
    graduation: "M.A.",
    furtherEducation: ["B.A.", "M.A."],
    taxClass: "2",
    familyStatus: FamilyStatus.Divorced,
    childCount: 1,
    sampleCompanyId: sampleCompanyIdMock,
    binaryFileId: null,
    note: "note",
    binaryFile: null
  }
]
