import {CodingCriterionFragment} from "../graphql/generated/CodingCriterionFragment"
import {
  ScenarioCodingAutomatedCriterionFragment,
  ScenarioCodingAutomatedCriterionFragment_DocumentViewScenarioCodingAutomatedCriterion,
  ScenarioCodingAutomatedCriterionFragment_FeatureUsageScenarioCodingAutomatedCriterion,
  ScenarioCodingAutomatedCriterionFragment_InputValueScenarioCodingAutomatedCriterion,
  ScenarioCodingAutomatedCriterionFragment_RScriptScenarioCodingAutomatedCriterion,
  ScenarioCodingAutomatedCriterionFragment_ToolUsageScenarioCodingAutomatedCriterion
} from "../graphql/generated/ScenarioCodingAutomatedCriterionFragment"

export type CodingCriterion = CodingCriterionFragment

export interface BaseCodingCriterion {
  readonly id: UUID
  readonly description: string
  readonly score: number
}

export type AutomatedCodingCriterion = ScenarioCodingAutomatedCriterionFragment

export type ToolUsageScenarioCodingAutomatedCriterion = ScenarioCodingAutomatedCriterionFragment_ToolUsageScenarioCodingAutomatedCriterion
export type DocumentViewScenarioCodingAutomatedCriterion = ScenarioCodingAutomatedCriterionFragment_DocumentViewScenarioCodingAutomatedCriterion
export type FeatureUsageScenarioCodingAutomatedCriterion = ScenarioCodingAutomatedCriterionFragment_FeatureUsageScenarioCodingAutomatedCriterion
export type InputValueScenarioCodingAutomatedCriterion = ScenarioCodingAutomatedCriterionFragment_InputValueScenarioCodingAutomatedCriterion
export type RScriptScenarioCodingAutomatedCriterion = ScenarioCodingAutomatedCriterionFragment_RScriptScenarioCodingAutomatedCriterion
