import {FreetextQuestionRatingCriterionSelectionFragment} from "../graphql/generated/FreetextQuestionRatingCriterionSelectionFragment"

export type FreetextQuestionRatingCriterionSelection = FreetextQuestionRatingCriterionSelectionFragment
