import {ParticipantProjectModuleProgressFragment} from "../graphql/generated/ParticipantProjectModuleProgressFragment"

export type ParticipantProjectModuleProgress = ParticipantProjectModuleProgressFragment
