import {ScenarioRatingCriterionSelectionFragment} from "../graphql/generated/ScenarioRatingCriterionSelectionFragment"

export type ScenarioRatingCriterionSelection = ScenarioRatingCriterionSelectionFragment
