import {Route as SharedRoute} from "shared/routes"

export enum Route {
  Scenarios = "route-scenarios",
  ScenarioCreation = "route-scenarios-create",
  ScenarioDetail = "route-scenarios-detail",
  ScenarioPreview = "route-scenarios-preview",
  ScenarioDetailIntroductionEmailCreation = "route-scenarios-detail-create-introduction-email",
  ScenarioEmails = "route-scenarios-emails",
  ScenarioEmailsEmailCreation = "route-scenarios-emails-create-email",
  ScenarioEmailsIntroductionEmailCreation = "route-scenarios-emails-create-introduction-email",
  ScenarioFiles = "route-scenarios-files",
  ScenarioCodingModelSelection = "route-scenarios-coding-models-selection",
  ScenarioCodingModelDetail = "route-scenarios-coding-model-detail",
  ScenarioCodingModelCreate = "route-scenarios-coding-model-create",
  ScenarioCodingDimensionDetail = "route-scenarios-coding-dimension-detail",
  ScenarioCodingItemDetail = "route-scenarios-coding-item-detail",
  ScenarioFilesDetail = "route-scenarios-files-detail",
  ScenarioDirectoriesDetail = "route-scenarios-directories-detail",
  ScenarioInterventions = "route-scenario-interventions",
  ScenarioInterventionsGroupTypeOverview = "route-scenario-interventions-position-overview",
  ScenarioInterventionsGroupEntityDetail = "route-scenario-interventions-position-detail",
  ScenarioInterventionsInterventionDetail = "route-scenario-interventions-intervention-detail",
  ScenarioInterventionsErpTableDetail = "route-scenario-interventions-erp-table-detail",
  ScenarioInterventionsErpRowInterventionDetail = "route-scenario-interventions-erp-row-intervention-detail",
  ScenarioQuestionnaireDetail = "route-scenarios-questionnaire-detail",
  ScenarioQuestionnaireDetailQuestion = "route-scenarios-questionnaire-detail-question",
  ScenarioQuestionnaireSelection = "route-scenarios-questionnaire-selection",
  ScenarioReferenceBookChapters = "route-scenarios-reference-book-chapters",
  ScenarioReferenceBookChaptersArticle = "route-scenarios-reference-book-chapters-article",
  ScenarioReferenceBookChaptersArticleDetail = "route-scenarios-reference-book-chapters-article-detail",
  ScenarioReferenceBookChaptersDetail = "route-scenarios-reference-book-chapters-detail",
  ScenarioReferenceBookChaptersSelection = "route-scenarios-reference-book-chapters-selection",
  ScenarioSampleCompanySelection = "route-scenarios-sample-company-selection",
  ScenarioSampleCompanySelectionPlaceholder = "route-scenarios-sample-company-selection-placeholder",
  ScenarioSampleCompanyDetail = "route-scenarios-sample-company-detail",
  ScenarioAssignedSampleCompanyDetail = "route-scenarios-assigned-sample-company-detail",
  ScenarioAssignedSampleCompanyDetailErp = "route-scenarios-assigned-sample-company-detail-erp",
  ScenarioAssignedSampleCompanyDetailErpTable = "route-scenarios-assigned-sample-company-detail-erp-table",
  ScenarioAssignedSampleCompanyDetailErpTableSelectedDataset = "route-scenarios-assigned-sample-company-detail-erp-table-selected-dataset",
  ScenarioInterventionsErpRowDetail = "route-scenarios-assigned-sample-company-detail-erp-row",
  ScenarioAssignedSampleCompanyDocuments = "route-scenarios-assigned-sample-company-documents",
  ScenarioAssignedSampleCompanyDocumentsDetails = "route-scenarios-assigned-sample-company-documents-details",
  ScenarioAssignedSampleCompanyDocumentsDetailsFile = "route-scenarios-assigned-sample-company-documents-details-file",
  ScenarioAssignedSampleCompanyDomainSignature = "route-scenarios-assigned-sample-companies-domain-signature",
  SampleCompanies = "route-sample-companies",
  SampleCompanyCreation = "route-sample-companies-create",
  SampleCompanyDetail = "route-sample-companies-detail",
  SampleCompanyDocuments = "route-sample-companies-documents",
  SampleCompanyDocumentDetails = "route-sample-companies-document-details",
  SampleCompanyDocumentDetailsFile = "route-sample-companies-document-details-file",
  SampleCompanyDomainSignature = "route-sample-companies-domain-signature",
  SampleCompanyErp = "route-sample-company-erp",
  Questionnaires = "route-questionnaires",
  QuestionnaireCreation = "route-questionnaires-creation",
  QuestionnaireDetail = "route-questionnaires-detail",
  QuestionnaireDetailQuestion = "route-questionnaires-detail-question",

  ReferenceBookChapters = "route-reference-book-chapters",
  ReferenceBookChaptersCreation = "route-reference-book-chapters-create",
  ReferenceBookChaptersDetail = "route-reference-book-chapters-detail",
  ReferenceBookChaptersDetailArticle = "route-reference-book-chapters-detail-article",
  ReferenceBookChaptersDetailArticleCreation = "route-reference-book-chapters-detail-article-create",
  ReferenceBookChaptersDetailArticleDetailsCreation = "route-reference-book-chapters-detail-article-details-create",
  MyAccount = "route-my-account",
  ResetPassword = "route-password-reset",
  Register = "route-register",
  Projects = "route-projects",
  ProjectCreation = "route-projects-create",
  ProjectDetail = "route-projects-detail",
  ScenarioSelection = "route-projects-scenario-selection",
  ScenarioSelectionDetail = "route-projects-scenario-selection-detail",
  QuestionnaireSelection = "route-projects-questionnaire-selection",
  QuestionnaireSelectionDetail = "route-projects-questionnaire-selection-detail",
  QuestionnaireSelectionDetailQuestion = "route-projects-questionnaire-selection-detail-question",
  SurveyCreation = "route-projects-survey-creation",
  TestSurveyCreation = "route-projects-test-survey-creation",
  SurveyEdit = "route-projects-survey-edit",
  SurveyDetail = "route-projects-survey-detail",

  SurveyMonitoringModule = "route-projects-survey-monitoring-module",
  SurveyMonitoringParticipant = "route-projects-survey-monitoring-participant",
  SurveyMonitoringParticipantScenario = "route-projects-survey-monitoring-participant-scenario",
  SurveyMonitoringParticipantQuestionnaire = "route-projects-survey-monitoring-participant-questionnaire",
  SurveyMonitoringParticipantScenarioScoring = "route-projects-survey-monitoring-participant-scenario-scoring",
  SurveyMonitoringParticipantQuestionnaireScoring = "route-projects-survey-monitoring-participant-questionnaire-scoring",

  SurveyScoring = "route-survey-scoring",
  SurveyScoringParticipant = "route-survey-scoring-participant",
  SurveyScoringParticipantScenario = "route-survey-scoring-participant-scenario",
  SurveyScoringParticipantQuestionnaire = "route-survey-scoring-participant-questionnaire",

  SurveyReporting = "route-survey-reporting",
  SurveyReportingParticipant = "route-survey-reporting-participant",
  SurveyReportingParticipantScenario = "route-survey-reporting-participant-scenario",
  SurveyReportingParticipantQuestionnaire = "route-survey-reporting-participant-questionnaire",
  SurveyReportingScenario = "route-survey-reporting-scenario",
  SurveyReportingQuestionnaire = "route-survey-reporting-questionnaire",
  SurveyReportingModule = "route-survey-reporting-module",
  SurveyReportingModuleScoringOverlay = "route-survey-reporting-module-scoring-overlay",

  RatingSurveyModuleAttendee = "route-rating-project-survey-module-attendee",
  RatingSurveyModuleAttendeeQuestion = "route-rating-project-survey-module-attendee-question",
  RatingSurveyModuleAttendeeScenario = "route-rating-project-survey-module-attendee-scenario",
  RaterRatingOverview = "route-rater-rating",
  RaterRatingDetails = "route-rater-rating-details",

  Events = "route-events",
  EventCreation = "route-events-creation",
  EventDetail = "route-events-detail",
  EventDetailQuestion = "route-events-detail-question",
  UserManagement = "route-user-management",
  RScripts = "route-r-scripts",
  RScriptsDetail = "route-r-scripts-detail"
}

export const routesMap = {
  [Route.Scenarios]: "/",
  [Route.Register]: "/register",
  [Route.ScenarioCreation]: "/scenarios/create",
  [Route.ScenarioCodingModelSelection]: "/scenarios/:scenarioId/coding-models",
  [Route.ScenarioCodingModelDetail]: "/scenarios/:scenarioId/coding-model/:codingModelId",
  [Route.ScenarioCodingModelCreate]: "/scenarios/:scenarioId/coding-models/create",
  [Route.ScenarioCodingDimensionDetail]: "/scenarios/:scenarioId/coding-model/:codingModelId/dimensions/:dimensionId",
  [Route.ScenarioCodingItemDetail]:
    "/scenarios/:scenarioId/coding-model/:codingModelId/dimensions/:dimensionId/items/:itemId",
  [Route.ScenarioDetail]: "/scenarios/:scenarioId",
  [Route.ScenarioPreview]: "/scenarios/:scenarioId/preview",
  [Route.ScenarioDetailIntroductionEmailCreation]: "/scenarios/:scenarioId/create-introduction-email",
  [Route.ScenarioEmails]: `/scenarios/:scenarioId/emails/:directory/:emailId?`,
  [Route.ScenarioEmailsEmailCreation]: "/scenarios/:scenarioId/emails/:directory/:emailId?/create-email",
  [Route.ScenarioEmailsIntroductionEmailCreation]:
    "/scenarios/:scenarioId/emails/:directory/:emailId?/create-introduction-email",
  [Route.ScenarioFiles]: "/scenarios/:scenarioId/files",
  [Route.ScenarioFilesDetail]: "/scenarios/:scenarioId/files/:fileId",
  [Route.ScenarioDirectoriesDetail]: "/scenarios/:scenarioId/directories/:directoryId",
  [Route.ScenarioInterventions]: "/scenarios/:scenarioId/interventions/:headerGroupType",
  [Route.ScenarioInterventionsErpTableDetail]: "/scenarios/:scenarioId/interventions/:headerGroupType/erp/:erpType",
  [Route.ScenarioInterventionsGroupTypeOverview]: "/scenarios/:scenarioId/interventions/:headerGroupType/:groupType",
  [Route.ScenarioInterventionsGroupEntityDetail]:
    "/scenarios/:scenarioId/interventions/:headerGroupType/:groupType/:groupEntityId",
  [Route.ScenarioInterventionsErpRowDetail]:
    "/scenarios/:scenarioId/interventions/:headerGroupType/erp/:erpType/rows/:rowId",
  [Route.ScenarioInterventionsErpRowInterventionDetail]:
    "/scenarios/:scenarioId/interventions/:headerGroupType/erp/:erpType/rows/:rowId/interventions/:interventionId",
  [Route.ScenarioInterventionsInterventionDetail]:
    "/scenarios/:scenarioId/interventions/:headerGroupType/:groupType/:groupEntityId/interventions/:interventionId",
  [Route.ScenarioReferenceBookChaptersSelection]: `/scenarios/:scenarioId/reference-book-chapters/select`,
  [Route.ScenarioSampleCompanySelection]: `/scenarios/:scenarioId/sample-companies/select`,
  [Route.ScenarioSampleCompanySelectionPlaceholder]: `/scenarios/:scenarioId/sample-companies`,
  [Route.ScenarioReferenceBookChapters]: `/scenarios/:scenarioId/reference-book-chapters/:referenceBookChapterId?`,
  [Route.ScenarioReferenceBookChaptersArticle]: `/scenarios/:scenarioId/reference-book-chapters/:referenceBookChapterId/article/:articleId`,
  [Route.ScenarioReferenceBookChaptersArticleDetail]: `/scenarios/:scenarioId/reference-book-chapters/:referenceBookChapterId/article/:articleId/details`,
  [Route.ScenarioReferenceBookChaptersDetail]: `/scenarios/:scenarioId/reference-book-chapters/:referenceBookChapterId/details`,
  [Route.ScenarioSampleCompanyDetail]: `/scenarios/:scenarioId/sample-companies/:sampleCompanyId`,
  [Route.ScenarioAssignedSampleCompanyDetail]: `/scenarios/:scenarioId/sample-companies/assigned/:sampleCompanyId`,
  [Route.ScenarioAssignedSampleCompanyDetailErp]: `/scenarios/:scenarioId/sample-companies/assigned/:sampleCompanyId/erp`,
  [Route.ScenarioAssignedSampleCompanyDetailErpTable]: `/scenarios/:scenarioId/sample-companies/assigned/:sampleCompanyId/erp/table/:erpType`,
  [Route.ScenarioAssignedSampleCompanyDetailErpTableSelectedDataset]: `/scenarios/:scenarioId/sample-companies/assigned/:sampleCompanyId/erp/table/:erpType/entity/:entityId`,
  [Route.ScenarioAssignedSampleCompanyDocuments]: `/scenarios/:scenarioId/sample-companies/assigned/:sampleCompanyId/documents`,
  [Route.ScenarioAssignedSampleCompanyDocumentsDetails]: `/scenarios/:scenarioId/sample-companies/assigned/:sampleCompanyId/documents/:directoryId`,
  [Route.ScenarioAssignedSampleCompanyDocumentsDetailsFile]: `/scenarios/:scenarioId/sample-companies/assigned/:sampleCompanyId/documents/:directoryId/:fileId`,
  [Route.ScenarioAssignedSampleCompanyDomainSignature]: `/scenarios/:scenarioId/sample-companies/assigned/:sampleCompanyId/domain-signature`,
  [Route.ScenarioQuestionnaireSelection]: `/scenarios/:scenarioId/questionnaires/select`,
  [Route.ScenarioQuestionnaireDetail]: `/scenarios/:scenarioId/questionnaires/:questionnaireId?`,
  [Route.ScenarioQuestionnaireDetailQuestion]: `/scenarios/:scenarioId/questionnaires/:questionnaireId/question/:questionId`,
  [Route.SampleCompanies]: "/sample-companies",
  [Route.SampleCompanyCreation]: "/sample-companies/create",
  [Route.SampleCompanyDetail]: "/sample-companies/:sampleCompanyId",
  [Route.SampleCompanyDocuments]: "/sample-companies/:sampleCompanyId/documents",
  [Route.SampleCompanyDocumentDetails]: "/sample-companies/:sampleCompanyId/documents/:directoryId",
  [Route.SampleCompanyDocumentDetailsFile]: "/sample-companies/:sampleCompanyId/documents/:directoryId/:fileId",
  [Route.SampleCompanyDomainSignature]: "/sample-companies/:sampleCompanyId/domain-signature",
  [Route.SampleCompanyErp]: "/sample-companies/:sampleCompanyId/erp",
  [Route.Questionnaires]: "/questionnaires",
  [Route.QuestionnaireCreation]: "/questionnaires/create",
  [Route.QuestionnaireDetail]: "/questionnaires/:questionnaireId",
  [Route.QuestionnaireDetailQuestion]: "/questionnaires/:questionnaireId/question/:questionId",
  [Route.ReferenceBookChaptersCreation]: "/reference-book-chapters/create",
  [Route.ReferenceBookChapters]: "/reference-book-chapters",
  [Route.ReferenceBookChaptersDetail]: "/reference-book-chapters/:id",
  [Route.ReferenceBookChaptersDetailArticle]: "/reference-book-chapters/:id/article/:articleId",
  [Route.ReferenceBookChaptersDetailArticleCreation]: "/reference-book-chapters/:id/article/create",
  [Route.ReferenceBookChaptersDetailArticleDetailsCreation]: "/reference-book-chapters/:id/article/:articleId/create",
  [Route.MyAccount]: "/my-account",
  [Route.ResetPassword]: "/reset-password/:email/:token",
  [Route.Projects]: "/projects",
  [Route.ProjectCreation]: "/projects/create",
  [Route.ScenarioSelection]: "/projects/:id/scenarios/select",
  [Route.ScenarioSelectionDetail]: "/projects/:id/scenarios/select/:scenarioId",
  [Route.QuestionnaireSelection]: "/projects/:id/questionnaires/select",
  [Route.QuestionnaireSelectionDetail]: "/projects/:id/questionnaires/select/:questionnaireId",
  [Route.QuestionnaireSelectionDetailQuestion]:
    "/projects/:id/questionnaires/select/:questionnaireId/question/:questionId",
  [Route.SurveyCreation]: "/projects/:id/surveys/create",
  [Route.TestSurveyCreation]: "/projects/:id/surveys/create-test",
  [Route.SurveyDetail]: "/projects/:id/surveys/:surveyId",
  [Route.SurveyEdit]: "/projects/:id/surveys/:surveyId/edit",

  [SharedRoute.SurveyMonitoring]: "/projects/:projectId/surveys/:surveyId/monitoring",
  [Route.SurveyMonitoringModule]: "/projects/:projectId/surveys/:surveyId/monitoring/module/:moduleId",
  [Route.SurveyMonitoringParticipant]:
    "/projects/:projectId/surveys/:surveyId/monitoring/participant/:surveyInvitationId",
  [Route.SurveyMonitoringParticipantScenario]:
    "/projects/:projectId/surveys/:surveyId/monitoring/participant/:surveyInvitationId/scenario/:scenarioId",
  [Route.SurveyMonitoringParticipantQuestionnaire]:
    "/projects/:projectId/surveys/:surveyId/monitoring/participant/:surveyInvitationId/questionnaire/:questionnaireId",
  [Route.SurveyMonitoringParticipantScenarioScoring]:
    "/projects/:id/surveys/:surveyId/monitoring/participant/:surveyInvitationId/scenario/:scenarioId/module/:moduleId/scoring",
  [Route.SurveyMonitoringParticipantQuestionnaireScoring]:
    "/projects/:id/surveys/:surveyId/monitoring/participant/:surveyInvitationId/questionnaire/:questionnaireId/module/:moduleId/scoring",

  [Route.SurveyScoring]: "/projects/:projectId/surveys/:surveyId/scoring",
  [Route.SurveyScoringParticipant]: "/projects/:projectId/surveys/:surveyId/scoring/participants/:surveyInvitationId",
  [Route.SurveyScoringParticipantScenario]:
    "/projects/:projectId/surveys/:surveyId/scoring/participant/:surveyInvitationId/scenario/:scenarioId",
  [Route.SurveyScoringParticipantQuestionnaire]:
    "/projects/:projectId/surveys/:surveyId/scoring/participant/:surveyInvitationId/questionnaire/:questionnaireId",

  [Route.SurveyReporting]: "/projects/:projectId/surveys/:surveyId/reporting",
  [Route.SurveyReportingParticipant]:
    "/projects/:projectId/surveys/:surveyId/reporting/participants/:surveyInvitationId",
  [Route.SurveyReportingParticipantScenario]:
    "/projects/:projectId/surveys/:surveyId/reporting/participants/:surveyInvitationId/scenario/:scenarioId",
  [Route.SurveyReportingParticipantQuestionnaire]:
    "/projects/:projectId/surveys/:surveyId/reporting/participants/:surveyInvitationId/questionnaire/:questionnaireId",
  [Route.SurveyReportingQuestionnaire]:
    "/projects/:projectId/surveys/:surveyId/reporting/:projectModuleId/questionnaire/:questionnaireId",
  [Route.SurveyReportingScenario]:
    "/projects/:projectId/surveys/:surveyId/reporting/:projectModuleId/scenario/:scenarioId",
  [Route.RatingSurveyModuleAttendee]:
    "/rating/projects/:projectId/surveys/:surveyId/modules/:moduleId/attendees/:surveyInvitationId",
  [Route.RatingSurveyModuleAttendeeQuestion]:
    "/rating/projects/:projectId/surveys/:surveyId/modules/:moduleId/attendees/:surveyInvitationId/questions/:questionId?",
  [SharedRoute.RatingOverviewSurveyModuleParticipantQuestionnaire]:
    "/projects/:id/surveys/:surveyId/rating/:surveyInvitationId/questionnaire/:moduleId",
  [SharedRoute.RatingOverviewSurveyModuleParticipantQuestionnaireNormalRater]:
    "/ratings/projects/:id/surveys/:surveyId/rating/:surveyInvitationId/questionnaire/:moduleId",
  [SharedRoute.RatingOverviewSurveyModuleParticipantQuestionnaireQuestion]:
    "/projects/:id/surveys/:surveyId/rating/:surveyInvitationId/questionnaire/:moduleId/question/:questionId?",
  [SharedRoute.RatingOverviewSurveyModuleParticipantQuestionnaireQuestionNormalRater]:
    "/ratings/projects/:id/surveys/:surveyId/rating/:surveyInvitationId/questionnaire/:moduleId/question/:questionId?",
  [SharedRoute.RatingOverviewSurveyModuleParticipantScenario]:
    "/projects/:id/surveys/:surveyId/rating/:surveyInvitationId/scenario/:moduleId",
  [SharedRoute.RatingOverviewSurveyModuleParticipantScenarioNormalRater]:
    "/ratings/projects/:id/surveys/:surveyId/rating/:surveyInvitationId/scenario/:moduleId",
  [SharedRoute.RatingOverviewSurveyModuleParticipantScenarioOverview]:
    "/projects/:id/surveys/:surveyId/rating/:surveyInvitationId/scenario/:moduleId/overview",
  [SharedRoute.RatingOverviewSurveyModuleParticipantScenarioOverviewNormalRater]:
    "/ratings/projects/:id/surveys/:surveyId/rating/:surveyInvitationId/scenario/:moduleId/overview",
  [SharedRoute.RatingOverviewSurveyModuleParticipantScenarioDimension]:
    "/projects/:id/surveys/:surveyId/rating/:surveyInvitationId/scenario/:moduleId/dimension/:dimensionId?",
  [SharedRoute.RatingOverviewSurveyModuleParticipantScenarioDimensionNormalRater]:
    "/ratings/projects/:id/surveys/:surveyId/rating/:surveyInvitationId/scenario/:moduleId/dimension/:dimensionId?",
  [Route.RatingSurveyModuleAttendeeScenario]:
    "/rating/projects/:projectId/surveys/:surveyId/modules/:moduleId/attendees/:surveyInvitationId/dimensions/:dimensionId?",

  [Route.UserManagement]: "/user-management",
  [Route.ProjectDetail]: "/projects/:id",
  [Route.Events]: "/events",
  [Route.EventCreation]: "/events/create",
  [Route.EventDetail]: "/events/:eventId",
  [Route.EventDetailQuestion]: "/events/:eventId/question/:questionId",
  [Route.RaterRatingOverview]: "/ratings",
  [Route.RaterRatingDetails]: "/ratings/survey/:surveyId",
  [Route.RScripts]: "/r-scripts",
  [Route.RScriptsDetail]: "/r-scripts/:rScriptId"
}
