import {ErpNavigationEntryId} from "../../../enums"
import {LucaTFunction} from "../../../translations"

export const erpEntryIdToLabel = (entryId: ErpNavigationEntryId, t: LucaTFunction, companyName: string) => {
  switch (entryId) {
    case ErpNavigationEntryId.Company:
      return companyName
    case ErpNavigationEntryId.UserManagement:
      return t("erp__navigation_label_user_management")
    case ErpNavigationEntryId.Office:
      return t("erp__navigation_label_office")
    case ErpNavigationEntryId.PhoneIntegration:
      return t("erp__navigation_label_phone_integration")
    case ErpNavigationEntryId.AppointmentCalendar:
      return t("erp__navigation_label_appointment_calendar")
    case ErpNavigationEntryId.OccupancyOfSpace:
      return t("erp__navigation_label_occupancy_of_space")
    case ErpNavigationEntryId.ApplicationSpanningComponents:
      return t("erp__navigation_label_application_spanning_components")
    case ErpNavigationEntryId.AuditManagement:
      return t("erp__navigation_label_audit_management")
    case ErpNavigationEntryId.eDocument:
      return t("erp__navigation_label_e_document")
    case ErpNavigationEntryId.Logistics:
      return t("erp__navigation_label_logistics")
    case ErpNavigationEntryId.MaterialsAdministration:
      return t("erp__navigation_label_materials_administration")
    case ErpNavigationEntryId.Suppliers:
      return t("erp__navigation_label_suppliers")
    case ErpNavigationEntryId.StockTake:
      return t("erp__navigation_label_stock_take")
    case ErpNavigationEntryId.Stock:
      return t("erp__navigation_label_stock")
    case ErpNavigationEntryId.ExternalTrade:
      return t("erp__navigation_label_external_trade")
    case ErpNavigationEntryId.Sales:
      return t("erp__navigation_label_sales")
    case ErpNavigationEntryId.CoreDataSales:
      return t("erp__navigation_label_core_data")
    case ErpNavigationEntryId.Customers:
      return t("erp__navigation_label_customers")
    case ErpNavigationEntryId.Products:
      return t("erp__navigation_label_products")
    case ErpNavigationEntryId.Shipping:
      return t("erp__navigation_label_shipping")
    case ErpNavigationEntryId.Billing:
      return t("erp__navigation_label_billing")
    case ErpNavigationEntryId.Offers:
      return t("erp__navigation_label_orders")
    case ErpNavigationEntryId.OrderItems:
      return t("erp__navigation_label_order_items")
    case ErpNavigationEntryId.Invoices:
      return t("erp__navigation_label_invoices")
    case ErpNavigationEntryId.Production:
      return t("erp__navigation_label_production")
    case ErpNavigationEntryId.Components:
      return t("erp__navigation_label_components")
    case ErpNavigationEntryId.ComponentsForProducts:
      return t("erp__navigation_label_components_for_products")
    case ErpNavigationEntryId.SalesPlanning:
      return t("erp__navigation_label_sales_planning")
    case ErpNavigationEntryId.ProductionPlanning:
      return t("erp__navigation_label_production_planning")
    case ErpNavigationEntryId.RequirementsPlanning:
      return t("erp__navigation_label_requirements_planning")
    case ErpNavigationEntryId.ProductCostPlanning:
      return t("erp__navigation_label_product_cost_planning")
    case ErpNavigationEntryId.CustomerService:
      return t("erp__navigation_label_customer_service")
    case ErpNavigationEntryId.QualityManagement:
      return t("erp__navigation_label_quality_management")
    case ErpNavigationEntryId.LogisticsControlling:
      return t("erp__navigation_label_logistics_controlling")
    case ErpNavigationEntryId.CoreFunctions:
      return t("erp__navigation_label_core_functions")
    case ErpNavigationEntryId.Accounting:
      return t("erp__navigation_label_accounting")
    case ErpNavigationEntryId.Finance:
      return t("erp__navigation_label_finance")
    case ErpNavigationEntryId.Controlling:
      return t("erp__navigation_label_controlling")
    case ErpNavigationEntryId.StrategicEnterpriseManagement:
      return t("erp__navigation_label_strategic_enterprise_management")
    case ErpNavigationEntryId.PropertyManagement:
      return t("erp__navigation_label_property_management")
    case ErpNavigationEntryId.Staff:
      return t("erp__navigation_label_staff")
    case ErpNavigationEntryId.StaffTable:
      return t("erp__navigation_label_staff_table")
    case ErpNavigationEntryId.StaffTimeManagement:
      return t("erp__navigation_label_staff_time_management")
    case ErpNavigationEntryId.Payroll:
      return t("erp__navigation_label_payroll")
    case ErpNavigationEntryId.TrainingNeedsManagement:
      return t("erp__navigation_label_training_needs_management")
    case ErpNavigationEntryId.InformationSystem:
      return t("erp__navigation_label_information_system")
    case ErpNavigationEntryId.InfoSystems:
      return t("erp__navigation_label_info_systems")
    case ErpNavigationEntryId.FinancialAnalytics:
      return t("erp__navigation_label_financial_analytics")
    case ErpNavigationEntryId.ProductLifecycleAnalytics:
      return t("erp__navigation_label_product_lifecycle_analytics")
    case ErpNavigationEntryId.Tools:
      return t("erp__navigation_label_tools")
    case ErpNavigationEntryId.Administration:
      return t("erp__navigation_label_administration")
    case ErpNavigationEntryId.WebClientUiFramework:
      return t("erp__navigation_label_web_client_ui_framework")
    case ErpNavigationEntryId.EnterpriseSearch:
      return t("erp__navigation_label_enterprise_search")
  }
}
