import {Salutation} from "shared/graphql/generated/globalTypes"
import {Scenario} from "shared/models"

export const scenariosMock: Scenario[] = [
  {
    __typename: "Scenario",
    id: "18de306c-a8f8-4311-9a2f-ca5418a245ac",
    name: "Scenario 1",
    description: "description",
    date: new Date(2021, 12, 1).toISOString(),
    maxDurationInSeconds: 5400,
    introductionEmailId: null,
    authorId: "psdfoj-sdöfois-sdf",
    completionEmailAddress: "test@test.de",
    shouldDisplayTime: false,
    shouldHideReferenceBookChapters: false,
    sampleCompany: null,
    sampleCompanyId: null,
    tags: [],
    createdAt: new Date(2021, 12, 1).toISOString(),
    modifiedAt: new Date(2021, 12, 1).toISOString(),
    finalizedAt: null,
    publishedAt: null,
    archivedAt: null,
    introductionEmail: null,
    codingModel: null,
    author: {
      __typename: "UserAccount",
      firstName: "Max",
      lastName: "Mustermann",
      id: "psdfoj-sdöfois-sdf",
      createdAt: new Date(2021, 12, 1).toISOString(),
      modifiedAt: new Date(2021, 12, 1).toISOString(),
      email: "max.mustermann@muster.de",
      organization: "Muster GmbH",
      salutation: Salutation.Mr,
      mayAdministrateUserAccounts: false,
      mayArchive: false,
      mayFinalizeWithoutPublishing: false,
      mayAdministrateRScripts: false
    }
  },
  {
    __typename: "Scenario",
    id: "18de306c-a8f8-4311-9a2f-dfdf",
    name: "Scenario 2",
    description: "description",
    date: "2020-08-03 06:16:28.504000 +00:00",
    maxDurationInSeconds: null,
    introductionEmailId: null,
    authorId: "psdfoj-sdöfois-sddsf",
    completionEmailAddress: "test@test.de",
    sampleCompany: null,
    sampleCompanyId: null,
    shouldDisplayTime: false,
    shouldHideReferenceBookChapters: false,
    tags: [],
    createdAt: new Date(2021, 12, 1).toISOString(),
    modifiedAt: new Date(2021, 12, 1).toISOString(),
    finalizedAt: null,
    publishedAt: null,
    archivedAt: null,
    introductionEmail: null,
    codingModel: null,
    author: {
      __typename: "UserAccount",
      firstName: "Max",
      lastName: "Mustermann",
      id: "psdfoj-sdöfois-sddsf",
      createdAt: new Date(2021, 12, 1).toISOString(),
      modifiedAt: new Date(2021, 12, 1).toISOString(),
      email: "max.mustermann@muster.de",
      organization: "Muster GmbH",
      salutation: Salutation.Mr,
      mayAdministrateUserAccounts: false,
      mayArchive: false,
      mayFinalizeWithoutPublishing: false,
      mayAdministrateRScripts: false
    }
  }
]
